タスクのCRUD機能の実装
yuta-git/backlog-app pull request #3
Opened 2024-01-13 01:32 UTC by yuta-git

タスクテーブルのCRUD機能に併せて、以下の画面を作成しました。
ご確認よろしくお願いいたします。

・一覧画面(プロジェクトの詳細画面)
・詳細画面
・作成画面
・修正画面

2024-01-13 12:30 UTC, MizukiMatsutani requested changes

2024-01-13 12:30 UTC, MizukiMatsutani commented on routes/web.php
> +Route::prefix('projects/{project_id}/tasks')
全体に入れやすいように
middleware(['auth'])だけのグループを大外で括ってたほうが良いかも！

あと、↑のRoute::prefix('projects')に入れ子で入れたほうがいいかもです！（ただcontrolerのグループが邪魔しそうですので、たとえば以下の感じ？

```
Route::middleware(['auth'])->group(function () {
    Route::prefix('projects')
        ->group(function () {
            Route::controller(ProjectController::class)
                ->name('projects.')
                ->group(funciton () {
                    //ここにprojectの各種ルーティング
                });

            Route::prefix('/{project_id}/tasks')
                ->controller(TaskController::class)
                ->name('tasks.')
                ->group(funciton () {
                    //ここにtaskの各種ルーティング
                });
        });
});
```

2024-01-13 12:30 UTC, MizukiMatsutani commented on resources/views/tasks/show.blade.php
> +                        {{ $task->deadline }}</div>
これ日付フォーマットする方法もありますよ！
`$task->deadline->format('Y年m月d日 hh時mm分ss秒') ` 

※ただし↑のほうで書いたModelの日付キャストをやってる必要がある

2024-01-13 12:30 UTC, MizukiMatsutani commented on app/Models/Task.php
> +
deadlineはcastで指定しておけばCarbonインスタンスとして変換されるので便利です！

```
protected $casts = [
    'deadline' => 'datetime',
];
```

https://readouble.com/laravel/10.x/ja/eloquent-mutators.html#date-casting

2024-01-13 12:30 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +        $task = Task::findOrFail($task_id); //find だとURLを直接いじられると落ちる
これでも良いですが、Laravelのリレーション機能を使うとさくっと紐づく値が取れますよ！！

2024-01-13 12:30 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +        $task = Task::findOrFail($task_id);
ここらへんもリレーションを使うとLaravelらしいです！

2024-01-13 12:30 UTC, MizukiMatsutani commented on app/Http/Controllers/ProjectController.php
> +        $tasks = $query->where('project_id', $project->id)->paginate(config('pagination.page_size'));
ここら辺もリレーションの機能を使うともっと簡潔に書けます！！

2024-01-16 10:32 UTC, MizukiMatsutani commented on app/Http/Controllers/ProjectController.php
> +        $tasks = $query->where('project_id', $project->id)->paginate(config('pagination.page_size'));
```
$tasks = Task::search($request->search)
      ->where('project_id', $id)
      ->paginate(config('pagination.page_size'));
```

```
$tasks = Task::search($request->search)
      ->whereHas('project', function ($query) use ($id) {
          $query->where('project_id', $id);
      })
      ->paginate(config('pagination.page_size'));
```

2025-08-27 11:25 UTC, yuta-git commented on routes/web.php
> +Route::prefix('projects/{project_id}/tasks')
修正しました!

2025-08-27 11:26 UTC, yuta-git commented on resources/views/tasks/show.blade.php
> +                        {{ $task->deadline }}</div>
以下のコードに修正しました!

$task->deadline->format('Y年m月d日)

2025-08-27 11:27 UTC, yuta-git commented on app/Models/Task.php
> +
上記コードを追記しました!

2025-08-27 11:29 UTC, yuta-git commented on app/Http/Controllers/TaskController.php
> +        $task = Task::findOrFail($task_id); //find だとURLを直接いじられると落ちる
Projectモデルに hasMany $this->hasMany(Task::class) を追記し、以下のコードに修正しました!
$project = Task::findOrFail($project_id)->project;　

2025-08-27 11:30 UTC, yuta-git commented on app/Http/Controllers/TaskController.php
> +        $task = Task::findOrFail($task_id);
上記と同じく以下のコードに修正しました。

$project = Task::findOrFail($project_id)->project;　

2025-08-27 11:31 UTC, yuta-git commented on app/Http/Controllers/ProjectController.php
> +        $tasks = $query->where('project_id', $project->id)->paginate(config('pagination.page_size'));
以下のコードに修正しました。

    // リレーションを利用したコードに書き換え
    $tasks = Task::search($request->search)
      ->where('project_id', $id)
      ->paginate(config('pagination.page_size'));

2025-08-28 12:17 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +    $task = Task::findOrFail($task_id); //find だとURLを直接いじられると落ちる
@yuta-git 
こちら、 `Task::findOrFail($project_id)` はあってますか？TaskテーブルのID列をプロジェクトIDで検索していることになります。。

また、二回Taskテーブルからデータ取ってますが、これをリレーション使えば記載を少なくできます。

```
$task = Task::findOrFail($task_id);
// $task->project; でtaskに紐づくprojectを取れます。
```

なので、bladeに渡すのは $task だけで、blade内で$task->projectとするだけでいいです！

2025-08-28 12:17 UTC, MizukiMatsutani commented on routes/web.php
> +              Route::get('/sub-tasks', 'show')->name('show');
実際の画面を見てないので、なんとも言えませんが、

/sub-tasksというURLなのにも関わらず、TaskControllerのshowメソッドはTaskからしかデータ取ってなさげです。
''だけでいいかもです。

2025-08-28 12:17 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +    $project = Project::findOrFail($project_id);
こちら、project_idがすでにあるのに、projectテーブルからデータ取得してIDを改めて取るのは非効率です！

そのままproject_idを使ってto_routeしていいかと！
存在するプロジェクトIDなのか検査する意味合いで入れていると思いますが、projectのshowでも同じように `$project = Project::findOrFail($id);` しているので重複しているので不要です！

2025-08-28 12:17 UTC, MizukiMatsutani commented on app/Http/Controllers/TaskController.php
> +    $task = Task::findOrFail($task_id);
ココもリレーションの書き方として、不自然です！

```
$project = Task::findOrFail($project_id)->project;
$task = Task::findOrFail($task_id);
```
のロジックは以下に書き換えることができます。

```
$task = Task::findOrFail($task_id);
$project = $task->project;  // わざわざ変数展開する必要もないですが、、、
```

2025-08-28 12:17 UTC, MizukiMatsutani commented on app/Http/Controllers/ProjectController.php
> +  public function update(Request $request, $id)
更新や、登録の時のリクエストパラメータは本来はバリデーションをかけたほうがいいですよ！
このPRでは対応しなくていいですが、対応はしておいた方がよいかと！
Laravel Fromリクエストという機能があります！

2025-09-03 13:12 UTC, yuta-git commented on app/Http/Controllers/TaskController.php
> +    $task = Task::findOrFail($task_id); //find だとURLを直接いじられると落ちる
修正しました!

2025-09-03 13:12 UTC, yuta-git commented on app/Http/Controllers/TaskController.php
> +    $project = Project::findOrFail($project_id);
修正しました!

2025-09-03 13:33 UTC, yuta-git commented on app/Http/Controllers/TaskController.php
> +    $task = Task::findOrFail($task_id);
修正しました!

2025-09-03 22:33 UTC, yuta-git commented on app/Http/Controllers/ProjectController.php
> +  public function update(Request $request, $id)
承知しました!　今後対応します!

2025-09-03 22:42 UTC, yuta-git commented on routes/web.php
> +              Route::get('/sub-tasks', 'show')->name('show');
今後、Taskの子どもにsubTaskテーブルを作成予定で、Task.show.blade 画面にsubTaskの一覧を表示させる予定です!

2025-09-04 13:05 UTC, merged